port: 9002
jwt:
  secret: "QuFsuM4dNSHfsfyjrCQeKAEE4KRj5sQR6Ez4Y6kcCh4XBgzJ43dHSm9mb9Y6kBBfUajgxjAbXRX4FttD"
sqs:
  region: us-west2
  endpoint: http://localhost:4566
sns:
  region: us-west2
  endpoint: http://localhost:4566
mongodb:
  database: inventory
  connection_string: mongodb://0.0.0.0:27017
events:
  items-updated: items-updated
